services:
    v12mike.imageredirect.listener:
        class: v12mike\imageredirect\event\listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }

